version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:81"     
      - "443:443"     
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - jenkins
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8081" 
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--httpPort=8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

